#!/usr/bin/env bash

SED=$(which sed)
CUT=$(which cut)
TR=$(which tr)
WC=$(which wc)

COMMENT="
/*
DO NOT EDIT
Autogenerated file by \`build_assets.sh\` at $(date).
*/
"

# build filePath package constName
build() {
    PATH="$1"
    FILEGO=${PATH}.go
    PACKAGE="$2"
    CONST="$3"

    [ ! -f $PATH ] && echo "couldn't find ${PATH}, skipping" && return

    echo "package ${PACKAGE}" > ${FILEGO}
    echo "${COMMENT}" >> ${FILEGO}
    echo "// ${CONST} - bundled asset, name should be self explaining." >> ${FILEGO}
    echo "const ${CONST} = \`" >> ${FILEGO}
    ${SED} 's/`/` + "`" + `/g' $PATH >> ${FILEGO}
    echo '`' >> ${FILEGO}
}

prebuild() {
    F="$1"
    PACKAGE=$(${CUT} -d ":" -f1 <<< "$F")
    FILENAME=$(${CUT} -d ":" -f2 <<< "$F")
    CONST=$(${CUT} -d ":" -f3 <<< "$F")
    build "./assets/${PACKAGE}/${FILENAME}" "${PACKAGE}" "${CONST}"
}

if [ ! -z $1 ]
then
    prebuild "$1"
    exit 0
fi

# directory:filename.ext:constName
FILES=(
    css:hack.css:HackCSS
    css:custom.css:CustomCSS

    templates:404.html:HTML404
    templates:dir.html:HTMLDirList
    templates:header.html:HTMLHeader
    templates:footer.html:HTMLFooter
    templates:about.html:HTMLAbout
    templates:pass.html:HTMLPassForm
)

for F in "${FILES[@]}"
do
    prebuild "$F"
done
