package css

/*
DO NOT EDIT
Autogenerated file by `build_assets.sh` at Mon Apr 16 11:29:14 EEST 2018.
*/

// CustomCSS - bundled asset, name should be self explaining.
const CustomCSS = `
em {
    font-style: italic !important;
}

.container.header {
    margin-top: 10vh;
}

.menu .menu-header {
    margin-top: 15px;
}
`
