package templates

/*
DO NOT EDIT
Autogenerated file by `build_assets.sh` at Thu Feb 28 23:01:41 EET 2019.
*/

// HTML404 - bundled asset, name should be self explanatory
const HTML404 = `
<div class="container">
    <div class="grid">
        <div class="cell -12of12">
            <div class="card">
                <header class="card-header">
                    <a href="/">~</a>/<a>404</a>/
                </header>
                <div class="card-content">
                    <div class="inner">
                        <div>
                            go <a href="javascript:window.history.go(-1);">back</a> or go back home on <a href="/">filekeep</a>.
                        </div>
                        {{if .}}
                            <div>
                                additionally, encountered error: {{.}}
                            </div>
                        {{end}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
`
