package templates

/*
DO NOT EDIT
Autogenerated file by `build_assets.sh` at Mon Apr 16 11:29:14 EEST 2018.
*/

// HTML404 - bundled asset, name should be self explaining.
const HTML404 = `
{{template "header"}}

<body class="hack">
<div class="container">
    <div class="grid">
        <div class="cell -12of12">
            <div class="card top">
                <header class="card-header">404 not found</header>
                <div class="card-content">
                    <div class="inner">
                        <div>
                            go <a href="javascript:window.history.go(-1);">back</a> or go back home on
                            <a href="/">filekeep</a>.
                        </div>
                    {{if .}}
                        <div>
                            additionally, encountered error: {{.}}
                        </div>
                    {{end}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

{{template "footer"}}
`
