package templates

/*
DO NOT EDIT
Autogenerated file by `build_assets.sh` at Thu Feb 28 23:01:41 EET 2019.
*/

// HTMLFooter - bundled asset, name should be self explanatory
const HTMLFooter = `
{{define "footer"}}

    <div class="container">
        <div class="grid -right">
            <div class="-12of12">
                <div class="footer-links">
                    <a href="/about">about</a>
                    |
                    <a href="/_toggleTheme">toggle theme</a>
                </div>
            </div>
        </div>
    </div>

    </body>
    </html>

{{end}}
`
