package templates

/*
DO NOT EDIT
Autogenerated file by `build_assets.sh` at Mon Apr 16 11:29:14 EEST 2018.
*/

// HTMLFooter - bundled asset, name should be self explaining.
const HTMLFooter = `
{{define "footer"}}
</body>
</html>
{{end}}
`
