package templates

/*
DO NOT EDIT
Autogenerated file by `build_assets.sh` at Thu Feb 28 23:01:41 EET 2019.
*/

// HTMLDirList - bundled asset, name should be self explanatory
const HTMLDirList = `
<div class="container">
    <div class="grid">
        <div class="cell -12of12">
            <div class="card">
                <header class="card-header">
                    listing
                    <strong>{{.Dirs | len}} director{{if eq (.Dirs | len) 1}}y{{else}}ies{{end}}</strong>
                    and
                    <strong>{{.Files | len}} file{{if not (eq (.Files | len) 1)}}s{{end}}</strong>
                    {{if .FilesSize}}({{.FilesSize}}){{end}}
                    in
                    {{range breadcrumbs .Path ""}}<a href="{{.Path}}">{{.Name}}</a>{{if not (eq .Name "")}}/{{end}}{{end}}
                </header>
                <div class="card-content">
                    <div class="inner -left">
                        <div class="menu">
                            {{if .Prev}}
                                <a class="menu-item" href="{{href .Prev}}">..</a>
                            {{end}}

                            {{/* Listing the directories */}}
                            {{if .Dirs | len}}
                                <div class="menu-header">dirs:</div>
                                {{range .Dirs}}
                                    <a class="menu-item" href="{{href .Path}}">
                                        {{.Name}}

                                        <div class="pull-right">
                                            {{if .Files | len}}
                                                {{.Files | len}} file{{if gt (.Files | len) 1}}s{{end}}
                                                ({{.FilesSize}})
                                            {{end}}

                                            {{if and (.Files | len) (.Dirs | len)}}
                                                and
                                            {{end}}

                                            {{if .Dirs | len}}
                                                {{.Dirs | len}} {{if eq (.Dirs | len) 1}}directory{{else}}directories{{end}}
                                            {{end}}

                                            {{if and (not (.Files | len)) (not (.Dirs | len))}}
                                                no items
                                            {{end}}
                                        </div>
                                    </a>
                                {{end}}
                            {{end}}

                            {{/* Listing the files */}}
                            {{if .Files | len}}
                                <div class="menu-header">files:</div>
                                {{range .Files}}
                                    <a class="menu-item" href="{{href .Path}}">
                                        {{.Name}}

                                        <div class="pull-right">
                                            {{.Size}}
                                        </div>
                                    </a>
                                {{end}}
                            {{end}}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
`
